project_id = "rfmrqdlizotzxbuiqhrx"

[functions.import-services]
verify_jwt = false

[functions.process-order]
verify_jwt = false

[functions.execute-organic-runs]
verify_jwt = false

[functions.check-order-status]
verify_jwt = false

[functions.process-engagement-order]
verify_jwt = false

[functions.execute-all-runs]
verify_jwt = false

[functions.cron-status]
verify_jwt = false

[functions.send-admin-alert]
verify_jwt = false

[functions.verify-usdt-deposit]
verify_jwt = false

[functions.get-exchange-rates]
verify_jwt = false

[functions.sync-service-prices]
verify_jwt = false

[functions.check-subscription-expiry]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.auto-verify-signup]
verify_jwt = false
[functions.sql-runner]
enabled = true
verify_jwt = true
import_map = "./functions/sql-runner/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sql-runner/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sql-runner/*.html" ]
